site_name: Android App Linking
site_url: https://github.com/SimonMarquis/Android-App-Linking
repo_name: Android App Linking
repo_url: https://github.com/SimonMarquis/Android-App-Linking
edit_uri: edit/master/docs/
site_description: "The ultimate developer guide to Android application linking methods"
site_author: Simon Marquis
remote_branch: gh-pages

copyright: 'Copyright &copy; 2023 Simon Marquis'

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true

plugins:
    - search

extra_css:
  - stylesheets/extra.css

nav:
  - '📋 Overview': index.md
  - '🔗 Methods':
    - 'Web url': web-url.md
    - 'App Links': app-links.md
    - 'Custom scheme': custom-scheme.md
    - 'Intent scheme': intent-scheme.md
    - 'App scheme': app-scheme.md
    - 'Firebase Dynamic Links': firebase-dynamic-links.md
    - 'Play Store url': play-store-url.md
    - 'Market scheme': market-scheme.md
  - '💎 Misc': misc.md
